### PR TITLE
Remove Infinest client

### PR DESCRIPTION
**Pull request by nicatronTg**
This pull request deletes all files in the repository.

Please accept it.

Thanks!

### CODE REVIEW

**Comment by Simon311** [comment]
Good PR, I agree with every change! :+1:

**Comment by Sergei-** [comment]
giphy
+1

**Comment by Enerdy** [comment]
:+1:

**Comment by Marcus101RR** [comment]
This needs to be removed, RE-LOGIC needs to be linked to this so they know where to go. This thing is quite dangerous and, its against the TOS of Re-Logic might I add.

**Comment by Simon311** [comment]
That didn't help.

**Comment by Enerdy** [comment]
This will happen eventually, with or without the owner's consent. Just a forewarn.

**Comment by nicatronTg** [comment]
@Marcus101RR joke ruined; you got the PR closed

**Pull request closed without merging**
